-- DDL

-- 1 drop the phone and box references/columns from user
ALTER TABLE "PHONE"."PHONE_USER" DROP CONSTRAINT PHONE_USER_BOX_FK;
ALTER TABLE "PHONE"."PHONE_USER" DROP CONSTRAINT PHONE_USER_LAND_PHONE_FK;
ALTER TABLE "PHONE"."PHONE_USER" DROP COLUMN BOX_ID;
ALTER TABLE "PHONE"."PHONE_USER" DROP COLUMN LANDLINE_PHONE_ID;

-- 2 add constraint/column in landline phone referencing user
ALTER TABLE PHONE."LANDLINE_PHONE" ADD "USER_ID" NUMBER;
ALTER TABLE "PHONE"."LANDLINE_PHONE" ADD CONSTRAINT "LAND_PHONE_USER_FK" FOREIGN KEY ("USER_ID")
REFERENCES "PHONE"."PHONE_USER" ("USER_ID") ENABLE;

-- 3 add constraint/column in landline phone referencing box
ALTER TABLE PHONE."LANDLINE_PHONE" ADD "BOX_ID" NUMBER;
ALTER TABLE "PHONE"."LANDLINE_PHONE" ADD CONSTRAINT "LAND_PHONE_BOX_FK" FOREIGN KEY ("BOX_ID")
REFERENCES "PHONE"."BOX" ("BOX_ID") ENABLE;

-- 4 remove city key and country key from land phone because they already exists in box
ALTER TABLE "PHONE"."LANDLINE_PHONE" DROP COLUMN CITY_PHONE_KEY;
ALTER TABLE "PHONE"."LANDLINE_PHONE" DROP COLUMN COUNTRY_PHONE_KEY;

-- 5 add column user status and user type to phone user
ALTER TABLE PHONE."PHONE_USER" ADD "USER_STATUS" NUMBER;
ALTER TABLE PHONE."PHONE_USER" ADD "USER_TYPE" NUMBER;

--6 create logistics table
CREATE TABLE "PHONE"."LOGISTICS" 
 (	"LOGISTICS_ID" NUMBER NOT NULL ENABLE,
"REQUESTER_USER_ID" NUMBER, 
"DELIVERY_TO_USER_ID" NUMBER,
"DELIVERY_TO_AREA_ID" NUMBER, 
"DELIVERY_TO_STREET" VARCHAR2(500 BYTE), 
"REQUEST_DATE" DATE, 
"STATUS" NUMBER, 
"DELIVERY_COMMENTS" VARCHAR2(500 BYTE), 
"GOODS_DESCRIPTION" VARCHAR2(500 BYTE),  
 CONSTRAINT "LOGISTICS_PK" PRIMARY KEY ("LOGISTICS_ID")  ENABLE, 
 CONSTRAINT "LOGISTICS_USER_FK3" FOREIGN KEY ("DELIVERY_TO_USER_ID")
  REFERENCES "PHONE"."PHONE_USER" ("USER_ID") ENABLE, 
 CONSTRAINT "LOGISTICS_USER_FK2" FOREIGN KEY ("REQUESTER_USER_ID")
  REFERENCES "PHONE"."PHONE_USER" ("USER_ID") ENABLE, 
 CONSTRAINT "LOGISTICS_AREA_FK" FOREIGN KEY ("DELIVERY_TO_AREA_ID")
  REFERENCES "PHONE"."AREA" ("AREA_ID") ENABLE
 );
