ALTER TABLE FEATURE  MODIFY (UI_STYLE VARCHAR2(100 CHAR) );

ALTER TABLE PHONE_USER ADD (ABOUT_ME CLOB );


ALTER TABLE PHONE_USER DROP CONSTRAINT PHONE_USER_LANDLINE_FK1;

ALTER TABLE PHONE_USER DROP COLUMN LANDLINE_PHONE_ID;