
Insert into PHONE_USER (USER_ID,LOGIN_NAME,LOGIN_PASSWORD,CREATION_DATE,F_NAME,M_NAME,L_NAME,ORGANIZATION_TYPE,EMAIL,ADDRESS,MOBILE_PHONE,ORGANIZATION_NAME,USER_STATUS,USER_TYPE) values (2,'Fatma','456',null,'koko','gamal','lolo',1,'koko@telego.com','mama home','010611','Housewife',1,1);





Insert into LANDLINE_PHONE (LANDLINE_PHONE_ID,PHONE_NUMBER,USER_ID,BOX_ID) values (2,50203049,2,1);
